<script>
var jieguo = false;
function check_exist(company_name){
	var auid = <?php echo !empty($info['auid']) ? $info['auid'] : 0 ?>;
	$.ajax({
		type: "POST",
		data: {company_name:company_name,auid:auid},
		url: "{{ url('advertiser/check_exist') }}",
		dataType: "json",
		async: false,
		success: function(res) {
			if(res['code'] != 1) {
				jieguo = false;
			}else{
				jieguo = true;
			}
		}
	});
}
//表单验证
function checkForm(){
	//广告主名称
	var ad_name = $.trim($('#ad_name').val());
	if(ad_name==''){
		tips_message('请填写广告主名称');
		$('#ad_name')[0].focus();
		return false;
	}
	if(ad_name.length>20){
		tips_message('广告主名称不能超过20个字符');
		$('#ad_name')[0].focus();
		return false;
	}
	//登录名
	var username = $.trim($('#username').val());
	if(username==''){
		tips_message('请填写登录名');
		$('#username')[0].focus();
		return false;
	}
	if(username.length>20){
		tips_message('登录名不能超过20个字符');
		$('#username')[0].focus();
		return false;
	}
	//密码
	var password = $.trim($('#password').val());
	if(password==''){
		tips_message('请填写密码');
		$('#password')[0].focus();
		return false;
	}
	if(password.length>20){
		tips_message('密码长度不能超过20个字符');
		$('#password')[0].focus();
		return false;
	}
	//公司网址
	var company_web = $.trim($('#company_web').val());
	if(company_web==''){
		tips_message('请填写公司网址');
		$('#company_web')[0].focus();
		return false;
	}
	if(company_web.length>40){
		tips_message('公司网址长度不能超过40个字符');
		$('#company_web')[0].focus();
		return false;
	}
	//公司名称
	var company_name = $.trim($('#company_name').val());
	if(company_name==''){
		tips_message('请填写公司名称');
		$('#company_name')[0].focus();
		return false;
	}
	if(company_name.length>40){
		tips_message('公司名称长度不能超过40个字符');
		$('#company_name')[0].focus();
		return false;
	}
	check_exist(company_name);
	if(jieguo == false){
		tips_message('公司名称已存在');
		$('#company_name')[0].focus();
		return false;
	}
	//公司注册地址
	var register_address = $.trim($('#register_address').val());
	if(register_address.length>40){
		tips_message('注册地址长度不能超过40个字符');
		$('#register_address')[0].focus();
		return false;
	}
	//注册号
    var register_num = $.trim($('#register_num').val());
    if(register_num){
    	if(register_num.length>40){
			tips_message('注册号长度不能超过40个字符');
			$('#register_num')[0].focus();
			return false;
		}
    	if (/^[a-z0-9]+$/i.test(register_num) == false) {
	        tips_message("注册号格式错误");
	        $('#register_num')[0].focus();
	        return false;
	    }
    }
    //联系人姓名
	var contact_name = $.trim($('#contact_name').val());
	if(contact_name.length>40){
		tips_message('联系人姓名长度不能超过40个字符');
		$('#contact_name')[0].focus();
		return false;
	}
	//联系人邮箱
    var contact_email = $.trim($('#contact_email').val());
    if(contact_email.length>40){
		tips_message('联系人邮箱长度不能超过40个字符');
		$('#contact_email')[0].focus();
		return false;
	}
    if(contact_email){
    	if (/^([0-9A-Za-z\-_\.]+)@([0-9a-z]+\.[a-z]{2,3}(\.[a-z]{2})?)$/g.test(contact_email) == false) {
	        tips_message("联系人邮箱格式错误，请重新输入");
	        $('#contact_email')[0].focus();
	        return false;
	    }
    }
    //联系人手机号
    var contact_phone = $.trim($('#contact_phone').val());
    if(contact_phone){
    	if (/^1[0-9]{10}$/.test(contact_phone) == false) {
	        tips_message("请输入正确手机号");
	        $('#contact_phone')[0].focus();
	        return false;
	    }
    }
    //联系人qq号
    var contact_qq = $.trim($('#contact_qq').val());
    if(contact_qq){
    	if (/^[1-9][0-9]{4,9}$/.test(contact_qq) == false) {
	        tips_message("请输入正确qq号");
	        $('#contact_qq')[0].focus();
	        return false;
	    }
    }

	return true;
}
$(function(){
	$('.image').viewer();
})
//图片验证
function test(file_name){
	var result = /\.[^\.]+/.exec(file_name);
	return result;
}
function onUploadImgChange(sender,img,obj){
	if(!$("#"+img).val()){
		return false;
	}
    if( $("#"+img).val() && !sender.value.match(/.jpg|.gif|.png|.bmp|.jpeg/i) ){
        tips_message('图片格式无效！');
		remove_file(img);
        return false;
    }
    var uid = $('#uid').val();
	// 图片名称后缀必须为小写，大些报错
	var b = test(sender.value);
	if( $("#"+img).val() && b!=".jpg" && b!=".gif" && b!=".png" && b!=".bmp" && b!=".jpeg" ){
		tips_message('后缀只支持小写格式！');
		if(!uid){
			remove_file(img);
		}else{
			var file = $("#"+img);
			file.after(file.clone().val(""));
			file.remove();
		}
		return false;
	}
	$('#'+file).siblings('input[type=hidden]').val('');
	var imgSrc = check_img(sender);
    var img_url = imgSrc;
    var newimg = new Image();
    newimg.src = img_url;
    // 加载完成执行
    newimg.onload = function(){
		/*var w = newimg.width;
		var h = newimg.height;
		if( (img == 'ap_imgurl' || img == 'bg_img' || img == 'bottom_color') && w!=640 ){
			tips_message('宽必须640');
			remove_file(img);
			return false;
		}*/
		var objPreview = document.getElementById(obj);
		$('#'+img+'_del').remove();
		str = '<button id="'+img+'_del" type="button" onclick="del_img(\''+img+'\');" >删除</button>';
		$('#'+obj).closest('img').after(str);
		var imgs = document.getElementById(img);
		if( sender.files && sender.files[0] ){
			objPreview.style.display = 'block';
			objPreview.style.width = '300px';
			objPreview.style.height = '200px';
			objPreview.src = window.URL.createObjectURL(imgs.files[0]);
		}
	}	
} 	
function del_img(img){
	if(confirm('是否确认删除？')) {
		remove_file(img);
	}
}
function remove_file(file){
	$('#'+file).siblings('input[type=hidden]').val('');
	$('#'+file+'_div').removeAttr('src').css('display','none');
	$('#'+file+'_del').remove();
	var file = $("#"+file);
	file.after(file.clone().val(""));
	file.remove();
	return false;
}
function check_img(obj){
   	var imgSrc = '';
  	if( obj.files && obj.files[0] ){
        if(getOs() == 'Chrome'){
            imgSrc = window.URL.createObjectURL(obj.files[0]);
        }else{
            imgSrc = window.URL.createObjectURL(obj.files[0]);
        }
    }else{
        //IE下，使用滤镜
        obj.select();
        //解决IE9下document.selection拒绝访问的错误
        if( navigator.appName == "Microsoft Internet Explorer" && navigator.appVersion.match(/9./i) == "9." ){
            obj.blur();
        }
        var imgSrc = document.selection.createRange().text;
        document.selection.empty();
    }
	return imgSrc;
}
function getOs(){ 
   	var OsObject = ""; 
   	if(isIE = navigator.userAgent.indexOf("MSIE") != -1){ 
        return "MSIE"; 
   	}
   	if(isFirefox = navigator.userAgent.indexOf("Firefox") != -1){ 
        return "Firefox";
   	}
   	if(isChrome = navigator.userAgent.indexOf("Chrome") != -1){
        return "Chrome";
   	}
   	if(isSafari = navigator.userAgent.indexOf("Safari") != -1){
        return "Safari"; 
   	}
    if(isOpera = navigator.userAgent.indexOf("Opera") != -1){
        return "Opera";
   	} 
}
</script>
<div class="content_inner">
<form action="{{ url('advertiser/write') }}" method="post" enctype="multipart/form-data" onsubmit="return checkForm()">
	<input type="hidden" name="uid" id="uid" {% if uid is not empty %}value="{{uid}}"{% endif %}>
	<div class="single_info account_info">
		<h3>账号信息</h3>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>广告主名称：</label>
			</div>
			<div class="form_control">
				<input type="text" name="ad_name" id="ad_name" {% if info['ad_name'] is not empty %}value="{{info['ad_name']}}" readonly="readonly"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>登录名：</label>
			</div>
			<div class="form_control">
				<input type="text" name="username" id="username" {% if info['username'] is not empty %}value="{{info['username']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>密码：</label>
			</div>
			<div class="form_control">
				<input type="text" name="password" id="password" {% if info['password'] is not empty %}value="{{info['password']}}"{% endif %} class="inputtext">
				<br><a onclick="$(this).siblings('input').val('')">清除密码</a>
			</div>
		</div>

		<h3>广告主信息</h3>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>公司网址：</label>
			</div>
			<div class="form_control">
				<input type="text" name="company_web" id="company_web" {% if info['company_web'] is not empty %}value="{{info['company_web']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>公司名称：</label>
			</div>
			<div class="form_control">
				<input type="text" name="company_name" id="company_name" {% if info['company_name'] is not empty %}value="{{info['company_name']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>注册地址：</label>
			</div>
			<div class="form_control">
				<input type="text" name="register_address" id="register_address" {% if info['register_address'] is not empty %}value="{{info['register_address']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>注册号：</label>
			</div>
			<div class="form_control">
				<input type="text" name="register_num" id="register_num" {% if info['register_num'] is not empty %}value="{{info['register_num']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>营业执照照片：</label>
			</div>
			<div class="form_control">
				<input type="hidden" name="business_img" id="business_img" {% if info['business_img'] is not empty %}value="{{ info['business_img'] }}"{% endif %} />
				<input type="file" name="yingye_img" id="yingye_img" onchange="onUploadImgChange(this, 'yingye_img', 'yingye_img_div')" />
				<div><img id="yingye_img_div" {% if info['business_img'] is not empty %}src="{{ IMG_URL~info['business_img'] }}" style="width:300px;height:200px"{% endif %} class='image' /></div>
				{% if info['business_img'] is not empty %}
				<button type="button" id="yingye_img_del" type="button" onclick="del_img('yingye_img');">删除</button>
				{% endif %} 				
			</div>
		</div>

		<h3>联系人信息</h3>
		<div class="form_item">
			<div class="form_label">
				<label>联系人姓名：</label>
			</div>
			<div class="form_control">
				<input type="text" name="contact_name" id="contact_name" {% if info['contact_name'] is not empty %}value="{{info['contact_name']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>联系人邮箱：</label>
			</div>
			<div class="form_control">
				<input type="text" name="contact_email" id="contact_email" {% if info['contact_email'] is not empty %}value="{{info['contact_email']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>手机号：</label>
			</div>
			<div class="form_control">
				<input type="text" name="contact_phone" id="contact_phone" {% if info['contact_phone'] is not empty %}value="{{info['contact_phone']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>QQ号码：</label>
			</div>
			<div class="form_control">
				<input type="text" name="contact_qq" id="contact_qq" {% if info['contact_qq'] is not empty %}value="{{info['contact_qq']}}"{% endif %} class="inputtext">
			</div>
		</div>
		<div class="form_btn_foot">
			<button class="btn btn_orange" type="submit" style="width:100px">提交</button>&nbsp;&nbsp;
			<a class="btn btn-default" href="javascript:history.back(-1)" style="width:100px">取消</a>
		</div>
	</div>
</form>
</div>