<meta charset="utf-8" />
<title>{{title}}</title>
<link type="text/css" href="{{ static_url('static/css/bootstrap.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link type="text/css" href="{{ static_url('static/css/index.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link type="text/css" href="{{ static_url('static/css/radio/build.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link type="text/css" href="{{ static_url('static/css/viewer.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link href="{{ static_url('assets/css/style.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link href="{{ static_url('static/css/colorPicker.css?_v=')~assetsVersion }}" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{{ static_url('static/css/jquery.coolautosuggest.css')}}" />

<script type="text/javascript" src="{{ static_url('static/js/My97DatePicker/WdatePicker.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript" src="{{ static_url('static/js/jquery-2.1.0.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('static/js/public.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('static/js/viewer.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('static/js/kindeditor/kindeditor-all-min.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('static/js/kindeditor/lang/zh-CN.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript" src="{{ static_url('static/js/bootstrap.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript" src="{{ static_url('static/js/jquery.coolautosuggest.js')}}"></script>
<script type="text/javascript" src="{{ static_url('static/js/colorPicker.js') }}"></script>
<script type="text/javascript" src="{{ static_url('static/js/popwin.js') }}"></script>
<script type="text/javascript" src="{{ static_url('static/js/clipboard.min.js') }}"></script>
<script type="text/javascript" src="{{ static_url('static/js/ajaxfileupload.js') }}"></script>
<script type="text/javascript" src="{{ static_url('static/js/cn_area.js') }}"></script>
