<div class="content_inner">
	<div class="manage_ad_position">
		<div class="search_box">
			<form action="{{ url('activity/index') }}" method="get">
				<input type="hidden" name="srch_type" value="{{ srch_type }}">
				<div class="form_item">
					<div class="form_label">
						<label>活动名称：</label>
					</div>
					<div class="form_control">
						<input type="text" name="name" value="{{ name }}" class="inputtext">
					</div>
				</div>
				<div class="form_item">
					<div class="form_label">
						<label>活动类型：</label>
					</div>
					<div class="form_control">
						<select name="type" class="inputtext">
							<option value="0">全部</option>
							<option {{ type==1?'selected':'' }} value="1">大转盘</option>
							<option {{ type==2?'selected':'' }} value="2">刮刮乐</option>
							<option {{ type==3?'selected':'' }} value="3">九宫格抽奖</option>
						</select>
					</div>
				</div>
				<div class="form_item">
					<div class="form_control">
						<button class="btn_orange" >搜索</button>
					</div>
				</div>
				<a href="{{ url('activity/add') }}" class="btn_orange pull_right">新建活动</a>
			</form>
			<div class="clear"></div>
		</div>
		<div class="table_box">
			<ul class="nav nav-tabs" style="padding-top:20px">
		    	<li class="{{ srch_type=='sh'?'active':'' }}" ><a href="{{ url('activity/index?srch_type=sh') }}"  aria-expanded="false">待审核</a></li>
		        <li class="{{ srch_type=='tg'?'active':'' }}" ><a href="{{ url('activity/index?srch_type=tg') }}"  aria-expanded="false">已通过</a></li>
		        <li class="{{ srch_type=='ntg'?'active':'' }}" ><a href="{{ url('activity/index?srch_type=ntg') }}"  >未通过</a></li>
		        <li class="{{ srch_type=='xj'?'active':'' }}" ><a href="{{ url('activity/index?srch_type=xj') }}"  >已下架</a></li>
		    </ul>
		    <ul class="tab-content">
				<li class="tab-pane active">
		    		<div class="btn-group">
				        <button class="btn btn-default checkall">全选</button>
				        <button class="btn btn-default no_checkall">反选 </button>
				    </div>
				    <div class="btn-group pull-right">
				    	{% if srch_type == 'sh' %}
				    	<button class="btn btn-default" onclick="batchSubmit('tg',0)">批量通过</button>
				    	<button class="btn btn-default" onclick="batchSubmit('bh',0)">批量驳回</button>
				    	{% elseif srch_type == 'tg' %}
				        <button class="btn btn-default" onclick="batchSubmit('xj',0)">批量下架</button>
						{% elseif srch_type == 'ntg' %}
						<button class="btn btn-default" onclick="batchSubmit('cx',0)">批量撤销</button>
						<button class="btn btn-default" onclick="batchSubmit('del',0)">批量删除</button>
						{% elseif srch_type == 'xj' %}
						<button class="btn btn-default" onclick="batchSubmit('del',0)">批量删除</button>
						{% endif %}
				    </div>
		    		<table cellpadding="0" cellspacing="0" class="tables">
						<thead>
							<tr>
								<th width="4%"></th>
								<th width="15%">活动名称</th>
								<th width="7%">活动类型</th>
								<th width="16%">奖品</th>
								<th width="10%">开始时间</th>
								<th width="10%">结束时间</th>
								<th width="7%">活动地址</th>
								<th width="11%">操作</th>
							</tr>
						</thead>
						<tbody>
						{% if list is not empty %}
						 	{% for key,val in list %}
								<tr>
									<td><input type="checkbox" name="aid" value="{{ val['aid'] }}"></td>
									<td>{{ val['name'] }}</td>
									<td>
										{% if val['type'] == 1 %}
											大转盘
										{% elseif val['type'] == 2 %}
											刮刮乐
										{% elseif val['type'] == 3 %}
											九宫格抽奖
										{% endif %}
									</td>
									<td>
										{% for kk,vv in val['prize'] %}
											{{ kk + 1 }}.{{vv['name']}}
											{% if vv['type'] !=5 %}
											({{vv['prize_num']}})个
											{% endif %}
											<br/>
										{% endfor %}
									</td>
									<td>{{ date('Y-m-d H:i:s', val['start_tm']) }}</td>
									<td>{{ date('Y-m-d H:i:s', val['end_tm']) }}</td>
									<td>
										<a class="blue copy" data-clipboard-text="http://activity.anzhi.com/Index/index?aid={{val['aid']}}">
											复制
										</a> |
										<a class="blue" target="_blank" href="http://activity.anzhi.com/Index/index?aid={{val['aid']}}">查看</a>

										
									</td>
									<td>
										{% if srch_type == 'sh' %}
										<a href="javascript:batchSubmit('tg',{{val['aid']}})" class="blue">通过</a>
										<a href="javascript:batchSubmit('bh',{{val['aid']}})" class="blue">驳回</a>
										<a href="{{ url('activity/add?aid='~val['aid']) }}" class="blue">编辑</a>
										<a href="{{ url('prize/index?aid='~val['aid']) }}" class="blue">奖品列表</a>
										{% elseif srch_type == 'tg' %}
										<a href="javascript:batchSubmit('xj',{{val['aid']}})" class="blue">下架</a>
										<a href="{{ url('activity/add?aid='~val['aid']) }}" class="blue">编辑</a>
										<a href="{{ url('prize/index?aid='~val['aid']) }}" class="blue">奖品列表</a>
										{% elseif srch_type == 'ntg' %}
										<a href="javascript:batchSubmit('cx',{{val['aid']}})" class="blue">撤销</a>
										<a href="javascript:batchSubmit('del',{{val['aid']}})" class="blue">删除</a>
										<a href="{{ url('activity/add?aid='~val['aid']) }}" class="blue">编辑</a>
										<a href="{{ url('prize/index?aid='~val['aid']) }}" class="blue">奖品列表</a>
										{% elseif srch_type == 'xj' %}
										<a href="javascript:batchSubmit('del',{{val['aid']}})" class="blue">删除</a>
										<a href="{{ url('prize/index?aid='~val['aid']) }}" class="blue">奖品列表</a>
										{% endif %}
									</td>
								</tr>
							{% endfor %}
						 {% else %}
								<tr>
			                        <td colspan="7">暂无数据</td>
			                    </tr>
						 {% endif %}
						</tbody>
					</table>
		    	</li>
		    </ul>
			{% if list is not empty %}
	             {{ partial('public/paginator') }}
	        {% endif %}
		</div>
	</div>
</div>

<script>
$(function(){
  $(".checkall").click(function(){  
      $("input[name='aid']").prop("checked", true);
  })
  $(".no_checkall").click(function(){  
      $("input[name='aid']").prop("checked", false); 
  })
})

function batchSubmit(type, id){
	var ids = '';
	var act = '';
	if( type == 'tg' ) {
		act = '通过'
	}else if( type == 'bh' ) {
		act = '驳回'
	}else if( type == 'xj' ) {
		act = '下架'
	}else if( type == 'del' ) {
		act = '删除'
	}else if( type == 'cx' ) {
		act = '撤销'
	}
	var cfm_notice = '确定要批量'+act;
	if(id > 0){
		ids = id;
		cfm_notice = '确定要'+act;
	}else{
		$("input[name='aid']:checkbox").each(function(){
		    if($(this).prop("checked")){
		      	var id_num = $(this).val();
		      	ids += id_num+',';
		    }
		});
		ids = ids.substr(0, ids.length-1);  
		if(ids == ''){
			alert('请选择媒体');
			return false;
		}
	}
	if(confirm(cfm_notice)){
		window.location.href="{{ url('activity/operation?type="+type+"&ids="+ids+"') }}";
	}
}

var clipboard = new Clipboard('.copy');
clipboard.on('success', function(e) {
   alert("复制链接成功！");

    e.clearSelection();
});
clipboard.on('error', function(e) {
    alert("复制链接失败！");
});
</script>
