<script>
$(function(){
	$('.image').viewer();
})
function search(){
	var pu_tid = $('#pu_tid').val();
	var status = {{status}};
	window.location.href="{{ url('guige/list?pu_tid="+pu_tid+"&status="+status+"') }}";
}
</script>
<div class="content_inner">
	<div class="manage_ad_position">
		<div class="search_box">
			<div class="form_item">
				<div class="form_label">
					<label>状态：</label>
				</div>
				<div class="form_control">
					<select id='pu_tid' class="inputtext" onchange="search()">
						{% for val in templates %}
							{% if val['id'] != 8 %}
							<option {% if pu_tid == val['id'] %}selected="selected"{% endif %} value="{{ val['id'] }}">{{ val['name'] }}</option>
							{% endif %}
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="form_item">
				<div class="form_control">
					{% if status==1 %}<!-- <button class="btn_orange" onclick="add_guige()">添加</button> -->{% endif %}
				</div>
			</div>
			{% if status==1 %}<!-- <a href="{{ url('guige/list?status=0') }}" class="btn_orange pull_right">已删除</a> -->{% endif %}
			{% if status==0 %}<a href="{{ url('guige/list?status=1') }}" class="btn_orange pull_right">未删除</a>{% endif %}
			<div class="clear"></div>
		</div>
		<div class="table_box">
			
			<table cellpadding="0" cellspacing="0" class="tables">
				<thead>
					<tr>
						<th width="20%" style="word-wrap:break-word;word-break:break-all">广告图片({{template['size']}})静态图</th>
						<th width="20%" style="word-wrap:break-word;word-break:break-all">广告图片({{template['size']}})动态图</th>
						<th width="20%">文字描述</th>
						<th width="10%">显示概率</th>
						<th width="20%">创建时间</th>
						<th width="10%">操作</th>
					</tr>
				</thead>
				<tbody>
				{% if list is not empty %}
				 	{% for key,val in list %}
						<tr>
							<td>{% if val['static_img'] is not empty %}<img class='image' src="{{IMG_URL~val['static_img']}}" width='100px' height='50px' />{% endif %}</td>
							<td>{% if val['dynamic_img'] is not empty %}<img class='image' src="{{IMG_URL~val['dynamic_img']}}" width='100px' height='50px' />{% endif %}</td>
							<td>{{ val['describe'] }}</td>
							<td>{{ val['probability'] }}</td>
							<td>{{ date('Y-m-d H:i:s', val['create_tm']) }}</td>
							<td>
								<!-- {% if status==1 %}
								<a class='blue' onclick="edit_guige({{ key }})">编辑 </a>
								<a class='blue' href="{{ url('guige/del?tid='~val['tid']~'&pu_tid='~pu_tid) }}" onclick="return confirm('是否删除')">删除</a>
								{% endif %} -->
							</td>
						</tr>
					{% endfor %}
				 {% else %}
						<tr>
	                        <td colspan="6">暂无数据</td>
	                    </tr>
				 {% endif %}
				</tbody>
			</table>
			{% if list is not empty %}
	             {{ partial('public/paginator') }}
	        {% endif %}
		</div>
	</div>
</div>
<div class="modal" id="guige_add" tabindex="-1" role="dialog"  aria-labelledby="modal_reject_colse">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">添加广告规格</h4>
			</div>
			<form action="{{ url('guige/write') }}" method="post" enctype="multipart/form-data" onsubmit="return add_submit()" >
			<input type='hidden' id="tid" name='tid' />
			<input type="hidden" value="{{ pu_tid }}" name="pu_tid" />
			<input type="hidden" value="{{ template['size'] }}" name="size" />
			<input type='hidden' name='static_img' id='static_img' />
			<input type='hidden' name='dynamic_img' id='dynamic_img' />
			<div class="single_info account_info">
				<div class="form_item">
					<div class="form_label" style="width:155px;">
						<label><font color="red">*</font>广告静态图片：</label>
					</div>
					{% if pu_tid == 1 %}
						<div class="form_control" style="width:63%">
						<input type="file" name="img_inset_static_320" id="img_inset_static_320" />
						格式：PNG,JPG,JPEG&nbsp;&nbsp;尺寸：(320*250)
						</div>
						<div class="form_label" style="width:155px;"></div>
						<div class="form_control" style="width:63%">
						<input type="file" name="img_inset_static_600" id="img_inset_static_600" />
						格式：PNG,JPG,JPEG&nbsp;&nbsp;尺寸：(600*500)
						</div>
					{% else %}
						<div class="form_control" style="width:63%">
							<input type="file" name="img_static" id="img_static" />
							格式：PNG,JPG,JPEG&nbsp;&nbsp;尺寸：({{template['size']}})
						</div>
					{% endif %}
				</div>
				<div class="form_item">
					<div class="form_label" style="width:155px;">
						<label><font color="red">*</font>广告动态图片：</label>
					</div>
					{% if pu_tid == 1 %}
						<div class="form_control" style="width:63%">
						<input type="file" name="img_inset_dynamic_320" id="img_inset_dynamic_320"/>
						格式：GIF&nbsp;&nbsp;尺寸：(320*250)
						</div>
						<div class="form_label" style="width:155px;"></div>
						<div class="form_control" style="width:63%">
						<input type="file" name="img_inset_dynamic_600" id="img_inset_dynamic_600" />
						格式：GIF&nbsp;&nbsp;尺寸：(600*500)
						</div>
					{% else %}
						<div class="form_control" style="width:63%">
						<input type="file" name="img_dynamic" id="img_dynamic" />
						格式：GIF&nbsp;&nbsp;尺寸：({{template['size']}})
						</div>
					{% endif %}
				</div>
				<div class="form_item">
					<div class="form_label" style="width:155px;">
						<label><font color="red">*</font>文字描述：</label>
					</div>
					<div class="form_control" style="width:63%">
						<input type="text" name="describe" id="describe" class="inputtext" >
						不超过30个字符
					</div>
				</div>

				<div class="form_item">
					<div class="form_label" style="width:155px;">
						<label><font color="red">*</font>显示概率：</label>
					</div>
					<div class="form_control" style="width:63%">
						<input type="text" name="probability" id="probability" class="inputtext" >
					</div>
				</div>				
			</div>
			<div class="modal-footer code-footer">
				<input type="submit" class="btn btn_orange" value="确定" style="width:100px" />&nbsp;&nbsp;
				<button type="button" class="btn btn-default"  data-dismiss="modal" style="width:100px">取消</button>
			</div>
			</form>
		</div>
	</div>
</div>
<script>
function add_guige(){
	$('#img_static').val('');
	$('#img_dynamic').val('');
	$('#tid').val('');
	$('#static_img').val('');
	$('#dynamic_img').val('');
	$('#describe').val('');
	$('#probability').val('');
	$('#guige_add').modal('show');
}
function edit_guige(key){
	$('#img_static').val('');
	$('#img_dynamic').val('');
	var info = <?php echo json_encode($list) ?>[key];
	$('#tid').val(info['tid']);
	$('#static_img').val(info['static_img']);
	$('#dynamic_img').val(info['dynamic_img']);
	$('#describe').val(info['describe']);
	$('#probability').val(info['probability']);
	$('#guige_add').modal('show');
}

var pu_tid = {{pu_tid}};
function add_submit(){
	if(pu_tid == 1) {
		var static_img = $('#static_img').val();
		var img_inset_static_320 = $('#img_inset_static_320').val();
		var img_inset_static_600 = $('#img_inset_static_600').val();
		if(static_img == '' && img_inset_static_320 == ''){
			alert('请上传广告静态320*250的图片');
			return false;
		}
		if(img_inset_static_320 && !img_inset_static_320.match(/.jpg|.png|.jpeg/i)){
			alert('广告静态320*250的图片只支持PNG,JPG,JPEG格式');
			return false;
		}
		if(static_img == '' && img_inset_static_600 == ''){
			alert('请上传广告静态600*500的图片');
			return false;
		}
		if(img_inset_static_600 && !img_inset_static_600.match(/.jpg|.png|.jpeg/i)){
			alert('广告静态600*500的图片只支持PNG,JPG,JPEG格式');
			return false;
		}

		var dynamic_img = $('#dynamic_img').val();
		var img_inset_dynamic_320 = $('#img_inset_dynamic_320').val();
		var img_inset_dynamic_600 = $('#img_inset_dynamic_600').val();
		if(dynamic_img == '' && img_inset_dynamic_320 == ''){
			alert('请上传广告动态320*250的图片');
			return false;
		}
		if(img_inset_dynamic_320 && !img_inset_dynamic_320.match(/.gif$/i)){
			alert('广告动态320*250的图片只支持gif格式');
			return false;
		}
		if(dynamic_img == '' && img_inset_dynamic_600 == ''){
			alert('请上传广告动态600*500的图片');
			return false;
		}
		if(img_inset_dynamic_600 && !img_inset_dynamic_600.match(/.gif$/i)){
			alert('广告动态600*500的图片只支持gif格式');
			return false;
		}
	}else {
		var static_img = $('#static_img').val();
		var dynamic_img = $('#dynamic_img').val();
		var img_static = $('#img_static').val();
		if(static_img == '' && img_static == ''){
			alert('请上传广告静态图片');
			return false;
		}
		if(img_static && !img_static.match(/.jpg|.png|.jpeg/i)){
			alert('广告静态图片只支持PNG,JPG,JPEG格式');
			return false;
		}
		var img_dynamic = $('#img_dynamic').val();
		if(dynamic_img == '' && img_dynamic == ''){
			alert('请上传广告动态图片');
			return false;
		}
		if(img_dynamic && !img_dynamic.match(/.gif$/i)){
			alert('广告动态图片只支持gif格式');
			return false;
		}
	}
	var describe = $.trim($('#describe').val());
	if(describe == ''){
		alert('请填写文字描述');
		return false;
	}
	if(describe.length>30){
		alert('文字描述不能超过30个字符');
		return false;
	}
	var probability = $.trim($('#probability').val());
	if(probability == ''){
		alert('请填写概率');
		return false;
	}
	if(!probability.match(/^\d+$/)){
		alert('概率应填写整数');
		return false;
	}
}
</script>