	<div class="main" style="padding:0">
		<div>
			<div class="content_inner">
				<div class="manage_ad_position">

					<div class="table_box">

					    <ul class="tab-content">
					    	<li id="a" class="tab-pane active">
	
					    		<table cellpadding="0" cellspacing="0" class="tables">
									<thead>
										<tr>
											<th>父级行业</th>
											<th>行业</th>
											<th>行业底价</th>
											<th>行业差价</th>
											<th>操作</th>
										</tr>
									</thead>
									<tbody>
                                       {% if list is not empty %}
				 	                                    {% for key,val in list %}
										<tr>
											<td>{{ val['parentname'] }}</td>
											<td>{{ val['name'] }}</td>
											<td>{{ val['price']/100 }}</td>
											<td>{{ val['diff_price']/100 }}</td>
											<td>
												<a href="#" class="blue" onclick="edit({{ val['id'] }},{{ val['price'] }},{{ val['diff_price'] }})" data-toggle="modal" data-target="#modal_reject">编辑</a>
											</td>
                                                                                </tr>
                                                                            {% endfor %}
                                                                        {% endif %}
									</tbody>
								</table>
					    	</li>
					    </ul>
	 		{% if list is not empty %}
	                    {{ partial('public/paginator') }}
	                {% endif %}
					</div>
					
				</div>
			</div>
		</div>
	</div>
	<!--获取代码弹窗-->
<div class="modal" id="modal_reject" tabindex="-1" role="dialog" aria-labelledby="modal_reject_colse">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">行业底价</h4>
			</div>
			<div class="modal-body modal-reject_cnt" style="width:100%">
                                <form action="{{url('config/industry')}}" method="post" class="form-horizontal" id="save-form">

					<div class="clear"></div>
					<div class="form_item martop15">
						<div class="form_label">
							<label>行业底价</label>
						</div>
						<div class="form_control">
							<input type="text" value="0"  name="set_price" class="inputtext" id="set_price">
							<input type="hidden" value="0"  name="set_id" id="set_id">
						</div>
					</div>
<br>
					<div class="form_item martop15">
						<div class="form_label">
							<label>行业差价</label>
						</div>
						<div class="form_control">
							<input type="text" value="0" class="inputtext" name="diff_price" id="diff_price">
						</div>
					</div>

				</form>
			</div>
			<div class="modal-footer code-footer">
				<button type="button" id="save-btn" class="btn btn-default">确定</button>
				<button type="button" class="btn btn-default"  data-dismiss="modal">取消</button>
			</div>
		</div>
	</div>
</div>

<script>
function edit(id,price,diff_price){
	$("#set_price").val(price/100);
	$("#diff_price").val(diff_price/100);
	$("#set_id").val(id);
}

    $('#save-btn').on('click', function(){
    	//tips_message('请填写行业底价');

        $('#save-form').submit();
    });
</script>
