<div class="content_inner">
<form action="{{ url('index/publish') }}" method="post" enctype="multipart/form-data" onsubmit="return checksubmit()">
	<input type="hidden" name="muid" id='muid' value="{{ user['muid'] }}">
	<div class="single_info account_info">
		<h3>账号信息</h3>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>媒体主名称：</label>
			</div>
			<div class="form_control">
				<input type="text" name="media_name" value="{{ user['media_name'] }}"  class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>公司名称：</label>
			</div>
			<div class="form_control">
				<input type="text" name="md_compnay_name" value="{{ user['md_compnay_name'] }}" class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>媒体简介：</label>
			</div>
			<div class="form_control">
				<textarea name="intro" id="intro" style="height:100px">{{ user['intro'] }}</textarea>
			</div>
		</div>
		<h3>媒体信息</h3>
		<div class="form_item">
			<div class="form_label">
				<label>媒体类型：</label>
			</div>
			<div class="form_control">
				<select name="media_type" id="media_type" onchange="select_media_type(this)" class="inputtext">
					<option {{ user['media_type']==1?'selected':'' }} value="1">个人</option>
					<option {{ user['media_type']==2?'selected':'' }} value="2">公司</option>
				</select>
			</div>
		</div>

		<h3>财务信息</h3>
		<div class="form_item">
			<div class="form_label">
				<label><font color="red">*</font>结算方案：</label>
			</div>
			<div class="form_control">
				<select name="scheme" id="scheme" class="inputtext">
					<option value="0">请选择</option>
					{% for key,val in plan %}
					<option {{ user['scheme']==val['id']?'selected':'' }} value="{{ val['id'] }}">{{ val['name'] }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form_label" style="text-align: left;">
				<span>修改后次日生效</span>
			</div>
		</div>

		<h3>联系人信息</h3>
		<div class="form_item">
			<div class="form_label">
				<label>商务联系人：</label>
			</div>
			<div class="form_control">
				<input type="text" name="contact_name" value="{{ user['contact_name'] }}" class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>联系人邮箱：</label>
			</div>
			<div class="form_control">
				<input type="text" name="email" value="{{ user['email'] }}" class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>手机号：</label>
			</div>
			<div class="form_control">
				<input type="text" name="phone" value="{{ user['phone'] }}" class="inputtext">
			</div>
		</div>
		<div class="form_item">
			<div class="form_label">
				<label>QQ号码：</label>
			</div>
			<div class="form_control">
				<input type="text" name="qq" value="{{ user['qq'] }}" class="inputtext">
			</div>
		</div>
		<div class="form_btn_foot">
			<button class="btn btn_orange" style="width:100px;" type="submit">提交</button>&nbsp;&nbsp;
			<a class="btn btn-default" style="width:100px;" href="{{ url('index/list') }}">取消</a>
		</div>
	</div>
</form>
</div>

<script>
function select_media_type(obj){
	var type = $(obj).val()
	if(type == 1){
		$('.person').show();
		$('.company').hide();
	}else{
		$('.person').hide();
		$('.company').show();
	}
}

function checksubmit() {
 	var muid 	   = $("#muid").val();
 	var md_compnay_name   = $("input[name='md_compnay_name']").val();
 	var intro 	   = $("#intro").val();
 	var scheme	   = $("#scheme").val();
	var media_name = $("input[name='media_name']").val();
	if( media_name == '' ) {
		tips_message('媒体名称不能为空', 'error') 			
		return false
	}
 	if( !max_length(media_name, 40) ){
		tips_message('媒体名称不能超过20个字符','error');
		return false;
	}
 	if( md_compnay_name == '' ) {
 		tips_message('公司名称不能为空', 'error') 			
 		return false
 	}
 	if( !max_length(md_compnay_name, 80) ){
		tips_message('公司名称不能超过40个字符','error');
		return false;
	}
	if( intro == '' ) {
 		tips_message('媒体简介不能为空', 'error') 			
 		return false
 	}
 	if( !max_length(intro, 200) ){
		tips_message('媒体简介不能超过100个字符','error');
		return false;
	}
 	if( scheme == 0 ) {
 		tips_message('请选择结算方案', 'error') 			
 		return false
 	}

 	var media_type = $("#media_type").val()

	//联系人姓名
	var contact_name = $("input[name='contact_name']").val()
	if( contact_name !='' ) {
		if( !max_length(contact_name, 80) ){
			tips_message('商务联系人姓名长度不能超过40个字符','error');
			return false;
		}
	}
 	var email  = $("input[name='email']").val()
 	if( email != '' ) {
		var myreg = /^([0-9A-Za-z\-_\.]+)@([0-9a-z]+\.[a-z]{2,3}(\.[a-z]{2})?)$/g;
	      if(!myreg.test(email))
	      {
	          tips_message('邮箱输入不合法', 'error') 
	          return false;             
	      }
 	}
 	var phone  = $("input[name='phone']").val()
 	if( phone != '' ) {
	 	if(!(/^1(3|4|5|7|8)\d{9}$/.test(phone))){ 
	        tips_message('手机号输入不合法', 'error')  
	        return false; 
	    } 
	}
	var qq  = $("input[name='qq']").val()
 	if( qq != '' ) {
	 	if(!(/^[1-9]\d{4,15}$/.test(qq))){ 
	        tips_message('QQ号输入不合法', 'error')  
	        return false; 
	    } 
	}
 }




</script>