
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>智盟广告</title>
		<link type="text/css" href="{{ static_url('asset/css/swiper.css') }}" rel="stylesheet" />
		<link type="text/css" href="{{ static_url('asset/css/index.css'~'?v1=1.0') }}" rel="stylesheet" />
		<script type="text/javascript" src="{{ static_url('asset/js/jquery-2.1.0.js') }}"></script>
		<script type="text/javascript" src="{{ static_url('asset/js/swiper.js') }}"></script>
		<script type="text/javascript">
			$(window).scroll(function (e) {
		    	var  scrollTop = $(window).scrollTop();
		        if (scrollTop >= 500) {
		            $(".nav_wrap").addClass('fixed');
		        } else {
		            $(".nav_wrap").removeClass('fixed');
		        }
		    });
		</script>
	</head>
	<body>
		<div class="nav_wrap">
			<div class="wrapper_inner">
				<h1 class="logo">
					<a href="/" title="智盟广告">智盟广告</a>
				</h1>
				<ul class="nav">
					<li class="current"><a href="default.html">流量变现</a></li>
					<li><a href="atv.html">青苗计划</a></li>
					<li><a href="about.html">关于我们</a></li>
					<li><a href="qa.html">常见问题</a></li>
					<li><a href="http://dev.anzhi.com/" target="_blank">开发者平台</a></li>
				</ul>
				{% if is_login == 1 %}
				<div class="login_info" style="width:69px">
					<a href="{{ url('index/index') }}">媒体管理</a>
				</div>
				{% else %}
				<div class="login_info" >
					<a href="{{ login_url['login'] }}">登录</a>
					<a href="{{ login_url['register'] }}" class="register_index">注册</a>
				</div>
				{% endif %}
				<div class="clear"></div>
			</div>
		</div>
		<div class="banner">
			<a href="{{ url('index/index') }}" class="banner_btn">马上变现</a>
		</div>
	    <div class="sec_second">
	    	<div class="wrapper_inner">
	    		<div class="comment fl">
					<h1 class="intro">
						<strong>安智优势</strong>
					</h1>
					<p>超过7年分发渠道运营积淀，安智具备强大数据匹配能力、海量优质广告主和新颖多样的广告形式，提供一站式变现解决方案，助力广大开发者获得丰厚的流量价值实现！</p>
				</div>
				<div class="picture fr">
					<img class="mountains" src="{{ static_url('asset/images/infor_01.png') }}">
				</div>
	    	</div>
	    </div>
	    <div class="sec_third">
	    	<div class="wrapper_inner">
	    		<div class="comment fr">
					<h1 class="intro">
						<strong>免费快捷接入超简单</strong>
					</h1>
					<p>免费快捷接入，只需创建媒体应用，无需管理，有专业的工作人员运营广告主实时竞价，投放到媒体最适合的广告，提升用户体验的同时帮助开发者流量变现最大化。</p>
				</div>
				<div class="picture fl">
					<img class="mountains" src="{{ static_url('asset/images/infor_02.png') }}">
				</div>
	    	</div>
	    </div>
	    <div class="sec_four">
	    	<div class="wrapper_inner">
	    		<div class="comment">
					<h1 class="intro">
						<strong>广告样式丰富回报高</strong>
					</h1>
					<p>满足媒体广告需求，覆盖市场上所有的主流广告样式，包括开屏、bannner 、信息流、激励视频、插屏、悬浮等标准广告位。与
数万家优质的广告主建立合作，覆盖电商、金融、教育、旅游行业，严格把控广告质量，确保充足的广告填充率。</p>
				</div>
				<div class="picture">
					<ul class="adv_list">
						<li>
							<img src="{{ static_url('asset/images/phone_01.png') }}" />
							<span>banner广告</span>
						</li>
						<li>
							<img src="{{ static_url('asset/images/phone_02.png') }}" />
							<span>开屏广告</span>
						</li>
						<li>
							<img src="{{ static_url('asset/images/phone_03.png') }}" />
							<span>悬浮广告</span>
						</li>
						<li>
							<img src="{{ static_url('asset/images/phone_04.png') }}" />
							<span>插屏广告</span>
						</li>
						<li style="margin-right: 0;">
							<img src="{{ static_url('asset/images/phone_05.png') }}" />
							<span>信息流广告</span>
						</li>
					</ul>
				</div>
	    	</div>
	    </div>
	    <div class="sec_five">
	    	<div class="wrapper_inner">
	    		<div class="comment">
					<h1 class="intro">
						<strong>透明化账单结算靠谱</strong>
					</h1>
					<p style="text-align: center;">一对一服务，保证流量快速变现，便捷的投放数据查询服务，次月5日准时对账，结算更靠谱。</p>
				</div>
				<div class="picture">
					<img class="mountains" src="{{ static_url('asset/images/infor_03.png') }}">
				</div>
	    	</div>
	    </div>
		<div class="sec_six">
			<div class="wrapper_inner">
				<div class="desc">
					<h1>合作媒体</h1>
				</div>
				<div class="app_list">
					<div class="swiper-container" id="focus_01">
						<div class="swiper-wrapper">
							<div class="swiper-slide">
								<ul>
									<li>
										<img src="{{ static_url('asset/images/links_01.png') }}" />
										<span>驾考宝典</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_02.png') }}" />
										<span>宝宝树孕育</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_03.png') }}" />
										<span>魔力视频</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_04.png') }}" />
										<span>铃声多多</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_05.jpg') }}" />
										<span>快递100</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_06.png') }}" />
										<span>中华万年历</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_07.png') }}" />
										<span>虎扑体育</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_08.png') }}" />
										<span>春雨医生</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_09.png') }}" />
										<span>新氧美容</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_10.png') }}" />
										<span>波克捕鱼</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_11.png') }}" />
										<span>我的世界</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_12.png') }}" />
										<span>消灭星星</span>
									</li>
									<div class="clear"></div>
								</ul>
							</div>
							<div class="swiper-slide">
								<ul>
									<li>
										<img src="{{ static_url('asset/images/links_13.png') }}" />
										<span>别踩白块儿</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_14.png') }}" />
										<span>汤姆猫跑酷</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_15.jpg') }}" />
										<span>驾校模拟</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_16.png') }}" />
										<span>火柴人传说</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_17.png') }}" />
										<span>天天过马路</span>
									</li>
									<li>
										<img src="{{ static_url('asset/images/links_18.png') }}" />
										<span>超级飞侠</span>
									</li>

									<div class="clear"></div>
								</ul>
							</div>
						</div>
					</div>
					<div class="swiper-button-next swiper-button-white"></div>
					<div class="swiper-button-prev swiper-button-white"></div>
				</div>
				<script type="text/javascript">
					var swiper = new Swiper('.swiper-container', {
						pagination: '.swiper-pagination',
						paginationClickable: true,
						nextButton: '.swiper-button-next',
        				prevButton: '.swiper-button-prev',
					});
				</script>
			</div>
		</div>
		<div class="footer_wrap">
			<div class="footer wrapper_inner">
				<h3><span>联</span>系我们</h3>
				<ul class="footer_r">
				    <li>
				    	<h4>企业QQ、邮箱</h4>
				        <div class="footer_qq">
				        	<a href="#" target="blank"><script type="text/javascript" src="http://static.b.qq.com/account/bizqq/js/wpa.js?type=1&amp;kfuin=800004609&amp;ws=www.anzhi.com&amp;btn1=%E4%BC%81%E4%B8%9AQQ%E4%BA%A4%E8%B0%88"></script><iframe id="iframediv1513586413530" scrolling="no" frameborder="0" width="102" height="24" allowtransparency="true" src="about:blank"></iframe></a>
				        </div>
				        <div class="footer_email">
				        	<a href="mailto:zhimeng@anzhi.com">zhimeng@anzhi.com </a>
				        </div>
				    </li>
	    		</ul>
	    		<ul class="footer_l">
	    			<li>
	    				<img src="{{ static_url('asset/images/code_01.png') }}">
	    				<span>关注公共号</span>
	    			</li>
	    			<li>
	    				<img src="{{ static_url('asset/images/code_02.png') }}">
	    				<span>关注公共号</span>
	    			</li>
	    			<li class="nomargin">
	    				<img src="{{ static_url('asset/images/code_03.png') }}">
	    				<span>关注微博</span>
	    			</li>
	    		</ul>
			</div>
		</div>

		<div class="footer_anzhi">
			<div class="footer_bg_anzhi">
			</div>
			<p>
				北京力天无限网络技术有限公司 版权所有<br>地址：北京市海淀区西小口路66号中关村东升科技园A-1号楼一层103  违法和不良信息举报电话：010-56358201　13366144805
		 举报邮箱：kefu@anzhi.com<br>
				<a href="http://www.anzhi.com/aboutus.php">关于我们</a>　|　<a href="http://www.anzhi.com/contact.php">联系我们</a>　|　<a href="http://www.anzhi.com/zp.php">安智社招</a>　|　<a href="http://campus.anzhi.com" target="_blank">安智校招</a>　|　<a href="http://www.anzhi.com/jzjk/index.htm" target="_blank">家长监护</a>  |　<a href="http://www.anzhi.com/sitemap/" target="_blank">网站地图</a> |　<a href="http://www.anzhi.com/cnaac.php">网民须知</a><br>
				京 ICP 证 101039 号  |  <a href="http://www.miitbeian.gov.cn" target="_blank">京ICP备10031276号-2</a>  |  <a href="/images/copyright1.jpg?v2" target="_blank">京网文[2015]0642-272号</a>  |  <script src="http://s19.cnzz.com/stat.php?id=3216547&amp;web_id=3216547&amp;show=pic1" language="JavaScript"></script><script src="http://c.cnzz.com/core.php?web_id=3216547&amp;show=pic1&amp;t=z" charset="utf-8" type="text/javascript"></script><a href="http://www.cnzz.com/stat/website.php?web_id=3216547" target="_blank" title="站长统计"><img border="0" hspace="0" vspace="0" src="http://icon.cnzz.com/img/pic1.gif"></a>
		<img src="{{ static_url('asset/images/beian.png') }}" style="display: inline-block">
		<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802021371" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">京公网安备 11010802021371号</a>
			</p>
			<div class="believe_links">
				<a class="anva_logo" href="http://white.anva.org.cn" target="_blank" style="display:block; width:55px; height:55px; margin:5px auto 0; background:url( {{ static_url('asset/images/anva_logo.png') }}) no-repeat;"></a>
			</div>
		</div>

	</body>
</html>
