
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>智盟广告</title>
		<link type="text/css" href="{{ static_url('asset/css/jquery.fullPage.css') }}" rel="stylesheet" />
		<link type="text/css" href="{{ static_url('asset/css/swiper.css') }}" rel="stylesheet" />
		<link type="text/css" href="{{ static_url('asset/css/index.css'~'?v1=1.0') }}" rel="stylesheet" />
	</head>
	<body>
		<div class="nav_wrap fixed">
			<div class="wrapper_inner">
				<h1 class="logo">
					<a href="/" title="智盟广告">智盟广告</a>
				</h1>
				<ul class="nav">
					<li><a href="default.html">流量变现</a></li>
					<li><a href="atv.html">青苗计划</a></li>
					<li><a href="about.html">关于我们</a></li>
					<li class="current"><a href="qa.html">常见问题</a></li>
					<li><a href="http://dev.anzhi.com/" target="_blank">开发者平台</a></li>
				</ul>
					{% if is_login == 1 %}
					<div class="login_info" style="width:69px">
						<a href="{{ url('index/index') }}">媒体管理</a>
					</div>
					{% else %}
					<div class="login_info" >
						<a href="{{ login_url['login'] }}">登录</a>
						<a href="{{ login_url['register'] }}" class="register_index">注册</a>
					</div>
					{% endif %}
				<div class="clear"></div>
			</div>
		</div>
	    <div class="question_wrap">
	    	<div class="wrapper_inner">
		    	<h3>常见问题</h3>
		    	<div class="question_type">
		    		<i>1</i>
		    		<h4>注册问题</h4>
		    	</div>
		    	<ul class="question_list">
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>怎样成为安智移动广告联盟会员？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>安智开发者不需要注册，直接使用Dev平台账号登录。</p>
		    			</div>
		    		</li>
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>应用多久能完成审核？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>应用的审核周期为1个工作日（节假日顺延）。</p>
		    			</div>
		    		</li>
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>是否可以修改安智移动广告联盟会员ID？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>联盟会员ID一旦注册成功将无法修改。</p>
		    			</div>
		    		</li>
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>媒体审核拒绝理由说明？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>（1）媒体名称请勿使用涉黄词语。<br>
		    					（2）媒体名称请勿使用敏感词语。<br>
		    					（3）关键词信息请去掉涉黄词语。<br>
		    					（4）关键词信息请去掉敏感词语。<br>
		    					（5）媒体信息中请勿使用涉黄词语。<br>
		    					（6）媒体信息中请勿使用敏感词语。
		    				</p>
		    			</div>
		    		</li>
		    	</ul>
		    	<div class="question_type">
		    		<i>2</i>
		    		<h4>财务问题</h4>
		    	</div>
		    	<ul class="question_list">
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>结算周期是多久？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>上一个自然月（每月1日至月末最后一天）。</p>
		    			</div>
		    		</li>
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>邮寄发票后到帐时间是多久？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>截止每月15号收到的发票，如发票审核无误，当月安排支付；&nbsp;每月15号以后收到的发票，如发票审核无误下个月安排支付。</p>
		    			</div>
		    		</li>
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>是否可以修改安智移动广告联盟会员ID？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>联盟会员ID一旦注册成功将无法修改。</p>
		    			</div>
		    		</li>
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>结算金额是否有限制结算金额？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>A：暂无限制。</p>
		    			</div>
		    		</li>
		    	</ul>
		    	<div class="question_type">
		    		<i>3</i>
		    		<h4>计费问题</h4>
		    	</div>
		    	<ul class="question_list">
		    		<li>
		    			<div class="question_title">
		    				<p><span class="question_mark">Q：</span>安智移动广告联盟的计费方式？</p>
		    			</div>
		    			<div class="question_ans">
		    				<p><span class="question_mark">A：</span>CPC(点击计费)和CPM(千次广告展示计费)两种方式。</p>
		    			</div>
		    		</li>
		    	</ul>
	    	</div>
	    </div>
		<div class="footer_wrap">
			<div class="footer wrapper_inner">
				<h3><span>联</span>系我们</h3>
				<ul class="footer_r">
				    <li>
				    	<h4>企业QQ、邮箱</h4>
				        <div class="footer_qq">
				        	<a href="#" target="blank"><script type="text/javascript" src="http://static.b.qq.com/account/bizqq/js/wpa.js?type=1&amp;kfuin=800004609&amp;ws=www.anzhi.com&amp;btn1=%E4%BC%81%E4%B8%9AQQ%E4%BA%A4%E8%B0%88"></script><iframe id="iframediv1513586413530" scrolling="no" frameborder="0" width="102" height="24" allowtransparency="true" src="about:blank"></iframe></a>
				        </div>
				        <div class="footer_email">
				        	<a href="mailto:zhimeng@anzhi.com">zhimeng@anzhi.com </a>
				        </div>
				    </li>
	    		</ul>
	    		<ul class="footer_l">
	    			<li>
	    				<img src="{{ static_url('asset/images/code_01.png') }}">
	    				<span>关注公共号</span>
	    			</li>
	    			<li>
	    				<img src="{{ static_url('asset/images/code_02.png') }}">
	    				<span>关注公共号</span>
	    			</li>
	    			<li class="nomargin">
	    				<img src="{{ static_url('asset/images/code_03.png') }}">
	    				<span>关注微博</span>
	    			</li>
	    		</ul>
			</div>
		</div>

		<div class="footer_anzhi">
			<div class="footer_bg_anzhi">
			</div>
			<p>
				北京力天无限网络技术有限公司 版权所有<br>地址：北京市海淀区西小口路66号中关村东升科技园A-1号楼一层103  违法和不良信息举报电话：010-56358201　13366144805
		 举报邮箱：kefu@anzhi.com<br>
				<a href="http://www.anzhi.com/aboutus.php">关于我们</a>　|　<a href="http://www.anzhi.com/contact.php">联系我们</a>　|　<a href="http://www.anzhi.com/zp.php">安智社招</a>　|　<a href="http://campus.anzhi.com" target="_blank">安智校招</a>　|　<a href="http://www.anzhi.com/jzjk/index.htm" target="_blank">家长监护</a>  |　<a href="http://www.anzhi.com/sitemap/" target="_blank">网站地图</a> |　<a href="http://www.anzhi.com/cnaac.php">网民须知</a><br>
				京 ICP 证 101039 号  |  <a href="http://www.miitbeian.gov.cn" target="_blank">京ICP备10031276号-2</a>  |  <a href="/images/copyright1.jpg?v2" target="_blank">京网文[2015]0642-272号</a>  |  <script src="http://s19.cnzz.com/stat.php?id=3216547&amp;web_id=3216547&amp;show=pic1" language="JavaScript"></script><script src="http://c.cnzz.com/core.php?web_id=3216547&amp;show=pic1&amp;t=z" charset="utf-8" type="text/javascript"></script><a href="http://www.cnzz.com/stat/website.php?web_id=3216547" target="_blank" title="站长统计"><img border="0" hspace="0" vspace="0" src="http://icon.cnzz.com/img/pic1.gif"></a>
		<img src="{{ static_url('asset/images/beian.png') }}" style="display: inline-block">
		<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802021371" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">京公网安备 11010802021371号</a>
			</p>
			<div class="believe_links">
				<a class="anva_logo" href="http://white.anva.org.cn" target="_blank" style="display:block; width:55px; height:55px; margin:5px auto 0; background:url( {{ static_url('asset/images/anva_logo.png') }}) no-repeat;"></a>
			</div>
		</div>

	</body>
</html>
