<div class="navigation">
	<div class="title">
		<a class="title_main" href="{{ url('strategy/index') }}">屏蔽策略管理</a>
	</div>
	{{ partial('public/top_sidebar') }}
</div>

<div class="content_inner">
	<div class="manage_ad_position">
		<div class="search_box">
			<form action="{{ url('strategy/index') }}" method="get">
				<div class="form_item">
					<div class="form_label">
						<label>屏蔽策略名称：</label>
					</div>
					<div class="form_control">
						<input type="text" name="keyword" value="{{ keyword }}" class="inputtext">
					</div>
				</div>
				<div class="form_item">
					<div class="form_control">
						<button class="btn_orange">搜索</button>
					</div>
				</div>
				<a href="{{ url('strategy/add') }}" class="btn_orange pull_right">新建屏蔽策略</a>
				<div class="clear"></div>
			</form>
		</div>
		<div class="table_box">
			<table cellpadding="0" cellspacing="0" class="tables">
				<thead>
					<tr>
						<th width="35%">屏蔽策略名称</th>
						<th width="30%">屏蔽内容</th>
						<th width="20%">创建时间</th>
						<th width="15%">操作</th>
					</tr>
				</thead>
				<tbody>
			{% if list is not empty %}
				 {% for key,val in list %}
					<tr>
						<td>{{ val['name'] }}</td>
						<td>
							{{ val['shield_industry']==1 ? '行业屏蔽<br/>':'' }}
							{{ val['shield_tag']==1 ? '活动标签<br/>':'' }}
							{{ val['url'] is not empty ? '广告url屏蔽':'' }}
						</td>
						<td>{{ date('Y-m-d H:i:s', val['create_tm']) }}</td>
						<td>
							<a href="{{ url('strategy/add?id='~val['strategyid']) }}" class="blue">修改</a>
							<a href="javascript:del_strategy({{ val['strategyid'] }})" class="blue">删除</a>
						</td>
					</tr>
				{% endfor %}
			{% else %}
						<tr>
	                          <td colspan="7">暂无数据</td>
	                    </tr>
			{% endif %}
				</tbody>
			</table>
			{% if list is not empty %}
	             {{ partial('public/paginator') }}
	        {% endif %}

		</div>
	</div>
</div>

<input type="hidden" id="modal_confirm_btn" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal_confirm">
<div class="modal" id="modal_confirm" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-body confirm_body" style="width:100%">
				<p class="title"></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default cancel" data-dismiss="modal">取消</button>
				<button type="button" class="btn btn_orange ok" data-dismiss="modal">确定</button>
			</div>
		</div>
	</div>
</div>

<script>
function del_strategy(id){
	if(id <= 0) {
		alert('参数有误')
		return 
	}
	var res = Common.confirm({
	      title: '确定要删除该屏蔽策略',
	      operate: function (reselt, opt) {
	          if (reselt) {
				window.location.href = "{{ url('strategy/delete?strategyid=') }}"+id;
	          } 
	      }
	  })
}
</script>