<div class="navigation">
	<div class="title">
		<a class="title_main" href="{{ url('index/index') }}">申请合作</a>
	</div>
	{{ partial('public/top_sidebar') }}
</div>

<div class="content_inner">
	<div class="single_info">
		{% if user_info is not empty %}
		<div class="form_item">
			<div class="form_label"  style="background-color: #D9D9D9; width:548px;text-align: left;    padding-left: 10px;">
			{% if user_info['status'] == 2 %}
				驳回理由：
				{% if user_info['bh_reason'] == 1 %}
					媒体关键词问题
				{% elseif user_info['bh_reason'] == 2 %}
					媒体简介问题
				{% elseif user_info['bh_reason'] == 3 %}
					软件包名问题  
				{% elseif user_info['bh_reason'] == 4 %}
					下载地址问题
				{% endif %}	
				{% if user_info['bh_explain'] is not empty %}
					<br/>
					详细说明：{{user_info['bh_explain']}}
				{% endif %}
			{% else %}
				合作申请已发出，请等待商务人员审核
			{% endif %}
			</div>
		</div>	
		{% endif %}
		<form action="{{ url('apply/publish') }}" method="post" class="media_info" onsubmit="return checksubmit()">
			<input type="hidden" name="muid" value="{{ user_info['muid'] }}">
			<div class="form_item">
				<div class="form_label">
					<font color="red">*</font>
					<label>公司名称：</label>
				</div>
				<div class="form_control">
					<input type="text" name="md_compnay_name" value="{{ user_info['md_compnay_name'] }}" placeholder="请填写公司名称" class="inputtext">
				</div>
			</div>

			<div class="form_item">
				<div class="form_label">
					<label>商务联系人：</label>
				</div>
				<div class="form_control">
					<input type="text" name="contact_name" value="{{ user_info['contact_name'] }}" placeholder="" class="inputtext">
				</div>
			</div>

			<div class="form_item">
				<div class="form_label">
					<font color="red">*</font>
					<label>邮箱：</label>
				</div>
				<div class="form_control">
					<input type="text" name="email" value="{{ user_info['email'] }}" placeholder="请输入邮箱，如不清楚请询问开发同学" class="inputtext">
				</div>
			</div>

			<div class="form_item">
				<div class="form_label">
					<font color="red">*</font>
					<label>手机号：</label>
				</div>
				<div class="form_control">
					<input type="text" name="phone" value="{{ user_info['phone'] }}" placeholder="请输入手机号" class="inputtext">
				</div>
			</div>

			<div class="form_item">
				<div class="form_label">
					<font color="red">*</font>
					<label>QQ号：</label>
				</div>
				<div class="form_control">
					<input type="text" name="qq" value="{{ user_info['qq'] }}" placeholder="请输入QQ号" class="inputtext">
				</div>
			</div>
			
			<div class="form_item">
				<div class="form_label">
					<font color="red">*</font>
					<label>简介：</label>
				</div>
				<div class="form_control">
					<textarea name="intro" id="intro" placeholder="请对您的媒体进行简要的描述。便于商务人员更好的未您服务">{{ user_info['intro'] }}</textarea>
				</div>
			</div>
			<div class="form_item">
				<div class="form_label">
				</div>
				<div class="form_control">
					 <a href="{{ static_url('apks/智盟广告协议.pdf') }}" target="_blank" class="blue">智盟广告协议</a>
				</div>
			</div>
			{% if user_info is empty or user_info['status'] == 2 %}
	             <div class="form_btn_foot">
					<button class="btn btn_orange" style="width:100px;" type="submit">申请合作</button>
				</div>
	        {% endif %}
		</form>
	</div>
</div>

<script>
function checksubmit() {
	var md_compnay_name = $("input[name='md_compnay_name']").val()
	if(md_compnay_name == ''  ) {
		tips_message('公司全称不能为空', 'error') 			
		return false
	}
	if( !max_length(md_compnay_name, 80)){
		tips_message('公司全称长度不能超过40个字符','error');
		return false;
	}
	//联系人姓名
	var contact_name = $("input[name='contact_name']").val()
	if( contact_name !='' ) {
		if( !max_length(contact_name, 80) ){
			tips_message('联系人姓名长度不能超过40个字符','error');
			return false;
		}
	}
 	var email  = $("input[name='email']").val()
 	if(email == ''  ) {
		tips_message('邮箱不能为空', 'error') 			
		return false
	}
 	if( email != '' ) {
		var myreg = /^([0-9A-Za-z\-_\.]+)@([0-9a-z]+\.[a-z]{2,3}(\.[a-z]{2})?)$/g;
	    if(!myreg.test(email))
	    {
	       tips_message('邮箱输入不合法', 'error') 
	       return false;             
	    }
 	}
 	var phone  = $("input[name='phone']").val()
 	if(phone == ''  ) {
		tips_message('手机号不能为空', 'error') 			
		return false
	}
 	if( phone != '' ) {
	 	if(!(/^1(3|4|5|7|8)\d{9}$/.test(phone))){ 
	        tips_message('手机号输入不合法', 'error')  
	        return false; 
	    } 
	}
	var qq  = $("input[name='qq']").val()
	if(qq == ''  ) {
		tips_message('QQ号不能为空', 'error') 			
		return false
	}
 	if( qq != '' ) {
	 	if(!(/^[1-9]\d{4,15}$/.test(qq))){ 
	        tips_message('QQ号输入不合法', 'error')  
	        return false; 
	    } 
	}

	//简介
	var intro = $("#intro").val()
	if( intro =='' ) {
		tips_message('请填写简介','error');
		return false;
	}
	if( !max_length(intro, 200) ) {
		tips_message('媒体简介不能超过100个字符', 'error')
		return false
	}

 }
 </script>
