<div class="navigation">
	<div class="title">
		<a class="title_main" href="{{ url('position/index') }}">广告位数据</a>
		<i></i>
		<a class="title_sub_title" href="#">
			每日数据
		</a>
	</div>
	{{ partial('public/top_sidebar') }}
</div>

<div class="content_inner">
	<div class="manage_ad_position">
		<div class="search_box">
			<form action="{{ url('statistics/advertdays') }}" id="search_form" method="get">
				<input type="hidden" name="ad_id" value="{{ media_info['id'] }}" />
				<input type="hidden" name="platform" value="{{ platform }}" />
				<div class="title">
				 <label>媒体名称：{{ media_info['name'] }}</label>&nbsp;
				 <label>系统平台：{{ platform }}</label>
				</div>
				<div class="form_item">
					<div class="form_label">
						<label>查询时间：</label>
					</div>
					<div class="form_control">
						<input class="inputtext" id="start_tm" name="start_tm" value="{{ start_tm }}" onfocus="WdatePicker({readOnly:true})" onchange="search_form()" />
						<span class='space'>~</span>
						<input class="inputtext" id="end_tm" name="end_tm" value="{{ end_tm }}" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd',readOnly:true})" onchange="search_form()" />
					</div>
				</div>
				<div class="form_item">
					<div class="form_control">
						<a class="btn_orange" href="{{ url('statistics/advertdays?export=1'~'&ad_id='~media_info['id']~'&platform='~platform~'&start_tm='~start_tm~'&end_tm='~end_tm~'&order_type='~order_type~'&order=') }} {{ order?0:1 }}" >导出</a>
					</div>
				</div>
				<div class="clear"></div>
			</form>
		</div>
		<div class="table_box">
			<table cellpadding="0" cellspacing="0" class="tables">
				<thead>
					<tr>
						<th>日期</th>
						<th>
							<!-- 曝光量 -->
							{% if order_type == 'exp' %}
									<a href="{{ url('statistics/advertdays?'~'ad_id='~media_info['id']~'&platform='~platform~'&start_tm='~start_tm~'&end_tm='~end_tm~'&order_type=exp&order='~order) }}">曝光量
									{% if order  == 1 %}
									<span class="blue">↑</span>↓
									{% else %}
									<span class="blue">↓</span>↑
									{% endif %}
									</a>
							{% else %}
								<a href="{{ url('statistics/advertdays?'~'ad_id='~media_info['id']~'&platform='~platform~'&start_tm='~start_tm~'&end_tm='~end_tm~'&order_type=exp&order='~order) }}">曝光量↓↑</a>
							{% endif %}
						</th>
						<th>
							<!-- 点击量 -->
							{% if order_type == 'click' %}
									<a href="{{ url('statistics/advertdays?'~'ad_id='~media_info['id']~'&platform='~platform~'&start_tm='~start_tm~'&end_tm='~end_tm~'&order_type=click&order='~order) }}">点击量
									{% if order  == 1 %}
									<span class="blue">↑</span>↓
									{% else %}
									<span class="blue">↓</span>↑
									{% endif %}
									</a>
							{% else %}
								<a href="{{ url('statistics/advertdays?'~'ad_id='~media_info['id']~'&platform='~platform~'&start_tm='~start_tm~'&end_tm='~end_tm~'&order_type=click&order='~order) }}">点击量↓↑</a>
							{% endif %}
						</th>
						<th>点击率</th>
						<th>
							<!-- 预计收益 -->
							{% if order_type == 'ear' %}
									<a href="{{ url('statistics/advertdays?'~'ad_id='~media_info['id']~'&platform='~platform~'&start_tm='~start_tm~'&end_tm='~end_tm~'&order_type=ear&order='~order) }}">预计收益
									{% if order  == 1 %}
									<span class="blue">↑</span>↓
									{% else %}
									<span class="blue">↓</span>↑
									{% endif %}
									</a>
							{% else %}
								<a href="{{ url('statistics/advertdays?'~'ad_id='~media_info['id']~'&platform='~platform~'&start_tm='~start_tm~'&end_tm='~end_tm~'&order_type=ear&order='~order) }}">预计收益↓↑</a>
							{% endif %}
						</th>
						<th>eCPM</th>
					</tr>
				</thead>
				<tbody>
			{% if list is not empty %}
				{% set exposure = 0,click=0,earnings=0 %}
				 {% for key,val in list %}
				 	{% set exposure = exposure + val['exposure'] %}
				 	{% set click = click + val['click'] %}
				 	{% set earnings = earnings + val['earnings'] %}
					<tr>
						<td>{{ val['create_date'] }}</td>
						<td>{{ val['exposure'] }}</td>
						<td>{{ val['click'] }}</td>
						<td>{{ click_rate(val['click'],val['exposure'])}}%</td>
						<td>￥{{ number_format(val['earnings']) }}</td>
						<td>{{ ecpm(val['exposure'],val['earnings']) }}</td>
					</tr>
				{% endfor %}
					<tr>
						<td>总计</td>
						<td>{{ exposure }}</td>
						<td>{{ click }}</td>
						<td>{{ click_rate(click,exposure) }}%</td>
						<td>￥{{ number_format(earnings) }}</td>
						<td>{{ ecpm(exposure,earnings) }}</td>
					</tr>
			{% else %}
					<tr>
	                    <td colspan="7">暂无数据</td>
	                </tr>
			{% endif %}
				</tbody>
			</table>
			{% if list is not empty %}
	             {{ partial('public/paginator') }}
	        {% endif %}
		</div>
		
	</div>
</div>

<script>
function search_form(){
	var start_tm = $('#start_tm').val();
	var end_tm   = $('#end_tm').val();
	if( start_tm !='' && end_tm !="" ) {
		$('#search_form').submit();
	}
	return false;
}
</script>